#cloud-config

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - sudo usermod -aG docker ubuntu

  # Install Docker Compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

  # Create a directory for our project
  - mkdir /home/ubuntu/reth_project && cd /home/ubuntu/reth_project

  # Pull Docker Images
  - docker pull ghcr.io/paradigmxyz/reth
  - docker pull prom/prometheus
  - docker pull grafana/grafana
  - docker pull sigp/lighthouse

  # Create docker-compose.yml file
  - printf 'version: "3.7"\nservices:\n  reth:\n    image: ghcr.io/paradigmxyz/reth\n    volumes:\n      - ./rethdata:/root/.local/share/reth/db\n    ports:\n      - "9000:9000"\n  prometheus:\n    image: prom/prometheus\n    ports:\n      - "9090:9090"\n  grafana:\n    image: grafana/grafana\n    ports:\n      - "3000:3000"\n  lighthouse:\n    image: sigp/lighthouse' > /home/ubuntu/reth_project/docker-compose.yml

  # Start the services
  - cd /home/ubuntu/reth_project && docker-compose up -d
