version: "3.8"

services:
  lite:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.lite
      args:
        BASE_IMAGE: python:3.12-slim
        COMFYUI_SHA: 8508df25691b0c9213049ab0d723610d3d8f9136
        PYTORCH_VERSION: 2.3.0
        WORKDIR: /workspace
    image: latitudesh/confyui:lite
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 22:22 # ssh
      - 8188:8188 # comfyui
      - 8888:8888 # jupyter server

  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.latest
      args:
        BASE_IMAGE: python:3.12-slim
        COMFYUI_SHA: 8508df25691b0c9213049ab0d723610d3d8f9136
        PYTORCH_VERSION: 2.3.0
        WORKDIR: /workspace
    image: latitudesh/confyui:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    # command: /bin/bash
    # tty: true
    # stdin_open: true
    ports:
      - 22:22 # ssh
      - 8188:8188 # comfyui
      - 8888:8888 # jupyter server
