version: "3.8"

services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.10-slim
        WEBUI_VERSION: 1.9.4
    image: latitudesh/automatic1111:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 22:22 # ssh
      - 8188:8188 # automatic1111 webui
      - 8888:8888 # jupyter server
    # command: /bin/bash
    # tty: true
    # stdin_open: true
