version: "3.8"

services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.10-slim
    image: latitudesh/sd-3-medium:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 8912:8912 # sd3 gradio
    # command: /bin/bash
    # tty: true
    # stdin_open: true
