version: "3.8"

services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: latitudesh/nvidia-fp8-ssh:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 22:22 # ssh